#!/usr/bin/env bash

# abort if we're already inside a TMUX session
[ "$TMUX" == "" ] || exit 0
# startup a "default" session if non currently exists
# tmux has-session -t _default || tmux new-session -s _default -d

# present menu for user to choose which workspace to open
PS3="Please choose your session: "
# shellcheck disable=SC2207
IFS=$'\n' && options=($(tmux list-sessions -F "#S" 2>/dev/null) "New Session" "New dev session" "zsh")
echo "Available sessions"
echo "------------------"
echo " "
select opt in "${options[@]}"
do
	case $opt in
		"New Session")
			read -rp "Enter new session name: " SESSION_NAME
			tmux new -s "$SESSION_NAME" -f ~/dotfiles/tmux/.config/tmux/new_ses.conf
			break
			;;
		"New dev session")
			~/scripts/newdevses
			break
			;;
		"zsh")
			zsh --login
			break;;
		*)
			tmux attach-session -t "$opt"
			break
			;;
	esac
done
